// Generated by js_of_ocaml 3.0.1
(function(d){"use strict";var
aa=500,ap=" : flags Open_text and Open_binary are not compatible",$="Sys_error",ao=224,an="Invalid_argument",s=1024,am="fs",D="jsError",_=57343,al=512,ak="End_of_file",aj="Failure",Y="Undefined_recursive_module",Z=" : flags Open_rdonly and Open_wronly are not compatible",X="([^/]*)",ai="Stack_overflow",g=128,c="",C="^",T=" : file already exists",U=2048,V=56320,W=240,f=248,ag="Not_found",ah="undefined",S="Assert_failure",m="/",ae="Sys_blocked_io",af="fd ",R="Out_of_memory",ad="Match_failure",ab="Division_by_zero",ac="static/",B=1e3,aV=0;function
u(){return aV++}function
au(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
a7(f){for(var
h=c,b=h,a,j,d=0,i=f.length;d<i;d++){a=f.charCodeAt(d);if(a<g){for(var
e=d+1;e<i&&(a=f.charCodeAt(e))<g;e++);if(e-d>al){b.substr(0,1);h+=b;b=c;h+=f.slice(d,e)}else
b+=f.slice(d,e);if(e==i)break;d=e}if(a<U){b+=String.fromCharCode(192|a>>6);b+=String.fromCharCode(g|a&63)}else
if(a<55296||a>=_)b+=String.fromCharCode(ao|a>>12,g|a>>6&63,g|a&63);else
if(a>=56319||d+1==i||(j=f.charCodeAt(d+1))<V||j>_)b+="\xef\xbf\xbd";else{d++;a=(a<<10)+j-56613888;b+=String.fromCharCode(W|a>>18,g|a>>12&63,g|a>>6&63,g|a&63)}if(b.length>s){b.substr(0,1);h+=b;b=c}}return h+b}function
aZ(b,a){if(a.repeat)return a.repeat(b);var
d=c,e=0;if(b==0)return d;for(;;){if(b&1)d+=a;b>>=1;if(b==0)return d;a+=a;e++;if(e==9)a.slice(0,1)}}function
a$(d,e,c){var
b=new
Array(c);for(var
a=0;a<c;a++)b[a]=d[e+a];return b}function
H(b,d,a){var
e=String.fromCharCode;if(d==0&&a<=4096&&a==b.length)return e.apply(null,b);var
f=c;for(;0<a;d+=s,a-=s)f+=e.apply(null,a$(b,d,Math.min(a,s)));return f}function
as(a){if(a.t==2)a.c+=aZ(a.l-a.c.length,"\0");else
a.c=H(a.c,0,a.c.length);a.t=0}function
a6(f){for(var
l=c,d=c,i,h,j,a,b=0,k=f.length;b<k;b++){h=f.charCodeAt(b);if(h<g){for(var
e=b+1;e<k&&(h=f.charCodeAt(e))<g;e++);if(e-b>al){d.substr(0,1);l+=d;d=c;l+=f.slice(b,e)}else
d+=f.slice(b,e);if(e==k)break;b=e}a=1;if(++b<k&&((j=f.charCodeAt(b))&-64)==g){i=j+(h<<6);if(h<ao){a=i-12416;if(a<g)a=1}else{a=2;if(++b<k&&((j=f.charCodeAt(b))&-64)==g){i=j+(i<<6);if(h<W){a=i-925824;if(a<U||a>=55295&&a<57344)a=2}else{a=3;if(++b<k&&((j=f.charCodeAt(b))&-64)==g&&h<245){a=j-63447168+(i<<6);if(a<65536||a>1114111)a=3}}}}}if(a<4){b-=a;d+="\ufffd"}else
if(a>65535)d+=String.fromCharCode(55232+(a>>10),V+(a&1023));else
d+=String.fromCharCode(a);if(d.length>s){d.substr(0,1);l+=d;d=c}}return l+d}function
a5(a){switch(a.t){case
9:return a.c;default:as(a);case
0:if(au(a.c)){a.t=9;return a.c}a.t=8;case
8:return a6(a.c)}}function
n(c,a,b){this.t=c;this.c=a;this.l=b}n.prototype.toString=function(){return a5(this)};function
G(a){var
b=9;if(!au(a))b=8,a=a7(a);return new
n(b,a,a.length)}function
aX(b,a){throw[0,b,a]}function
a(a){return new
n(0,a,a.length)}function
az(c,b){aX(c,a(b))}var
b=[0];function
j(a){az(b.Sys_error,a)}var
o=new
Array();function
aR(e){var
a=o[e];if(!a.opened)j("Cannot flush a closed channel");if(!a.buffer||a.buffer==c)return 0;if(a.fd&&b.fds[a.fd]&&b.fds[a.fd].output){var
d=b.fds[a.fd].output;switch(d.length){case
2:d(e,a.buffer);break;default:d(a.buffer)}}a.buffer=c;return 0}if(d.process&&d.process.cwd)var
t=d.process.cwd().replace(/\\/g,m);else
var
t="/static";if(t.slice(-1)!==m)t+=m;function
aQ(a){a=a
instanceof
n?a.toString():a;if(a.charCodeAt(0)!=47)a=t+a;var
e=a.split(m),b=[];for(var
d=0;d<e.length;d++)switch(e[d]){case"..":if(b.length>1)b.pop();break;case".":break;case"":if(b.length==0)b.push(c);break;default:b.push(e[d]);break}b.orig=a;return b}function
aW(a){a=a
instanceof
n?a.toString():a;j(a+": No such file or directory")}function
a1(a){return new
n(4,a,a.length)}function
at(a){az(b.Invalid_argument,a)}function
aC(){at("index out of bounds")}function
a3(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
a0(b,a){if(a>>>0>=b.l)aC();return a3(b,a)}function
p(a){if(a<0)at("String.create");return new
n(a?2:9,c,a)}function
aw(a){return a.l}function
F(b){if(d.Uint8Array)var
c=new(d.Uint8Array)(b.l);else
var
c=new
Array(b.l);var
f=b.c,e=f.length,a=0;for(;a<e;a++)c[a]=f.charCodeAt(a);for(e=b.l;a<e;a++)c[a]=0;b.c=c;b.t=4;return c}function
w(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?H(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?H(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)F(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}function
aq(){}function
e(a){this.data=a}e.prototype=new
aq();e.prototype.truncate=function(a){var
b=this.data;this.data=p(a|0);w(b,0,this.data,0,a)};e.prototype.length=function(){return aw(this.data)};e.prototype.write=function(b,d,g,a){var
c=this.length();if(b+a>=c){var
e=p(b+a),f=this.data;this.data=e;w(f,0,this.data,0,c)}w(d,g,this.data,b,a);return 0};e.prototype.read=function(c,a,d,b){var
e=this.length();w(this.data,c,a,d,b);return 0};e.prototype.read_one=function(a){return a0(this.data,a)};e.prototype.close=function(){};e.prototype.constructor=e;function
h(b,a){this.content={};this.root=b;this.lookupFun=a}h.prototype.nm=function(a){return this.root+a};h.prototype.lookup=function(b){if(!this.content[b]&&this.lookupFun){var
c=this.lookupFun(a(this.root),a(b));if(c!=0)this.content[b]=new
e(c[1])}};h.prototype.exists=function(a){if(a==c)return 1;var
d=a+m,e=new
RegExp(C+d);for(var
b
in
this.content)if(b.match(e))return 1;this.lookup(a);return this.content[a]?1:0};h.prototype.readdir=function(d){var
g=d==c?c:d+m,h=new
RegExp(C+g+X),e={},b=[];for(var
f
in
this.content){var
a=f.match(h);if(a&&!e[a[1]]){e[a[1]]=true;b.push(a[1])}}return b};h.prototype.is_dir=function(a){var
e=a==c?c:a+m,f=new
RegExp(C+e+X),g=[];for(var
d
in
this.content){var
b=d.match(f);if(b)return 1}return 0};h.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};h.prototype.open=function(a,b){if(b.rdonly&&b.wronly)j(this.nm(a)+Z);if(b.text&&b.binary)j(this.nm(a)+ap);this.lookup(a);if(this.content[a]){if(this.is_dir(a))j(this.nm(a)+" : is a directory");if(b.create&&b.excl)j(this.nm(a)+T);var
c=this.content[a];if(b.truncate)c.truncate();return c}else
if(b.create){this.content[a]=new
e(p(0));return this.content[a]}else
aW(this.nm(a))};h.prototype.register=function(c,b){if(this.content[c])j(this.nm(c)+T);if(b
instanceof
n)this.content[c]=new
e(b);else
if(b
instanceof
Array)this.content[c]=new
e(a1(b));else
if(b.toString){var
d=a(b.toString());this.content[c]=new
e(d)}};h.prototype.constructor=h;function
ar(a){if(a.t!=4)F(a);return a.c}function
a4(a,c,b){b&=255;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}F(a)}a.c[c]=b;return 0}function
a2(b,a,c){if(a>>>0>=b.l)aC();return a4(b,a,c)}var
E=d.Buffer;function
l(a){this.fs=require(am);this.fd=a}l.prototype=new
aq();l.prototype.truncate=function(a){this.fs.ftruncateSync(this.fd,a|0)};l.prototype.length=function(){return this.fs.fstatSync(this.fd).size};l.prototype.write=function(g,b,c,f){var
a=ar(b);if(!a
instanceof
d.Uint8Array)a=new(d.Uint8Array)(a);var
e=new
E(a);this.fs.writeSync(this.fd,e,c,f,g);return 0};l.prototype.read=function(h,e,c,g){var
a=ar(e);if(!(a
instanceof
d.Uint8Array))a=new(d.Uint8Array)(a);var
f=new
E(a);this.fs.readSync(this.fd,f,c,g,h);for(var
b=0;b<g;b++)a2(e,c+b,f[c+b]);return 0};l.prototype.read_one=function(c){var
b=new(d.Uint8Array)(1),a=new
E(b);this.fs.readSync(this.fd,a,0,1,c);return a[0]};l.prototype.close=function(){this.fs.closeSync(this.fd)};l.prototype.constructor=l;function
k(a){this.fs=require(am);this.root=a}k.prototype.nm=function(a){return this.root+a};k.prototype.exists=function(a){return this.fs.existsSync(this.nm(a))?1:0};k.prototype.readdir=function(a){return this.fs.readdirSync(this.nm(a))};k.prototype.is_dir=function(a){return this.fs.statSync(this.nm(a)).isDirectory()?1:0};k.prototype.unlink=function(a){var
b=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a));return b};k.prototype.open=function(f,c){var
a=require("constants"),b=0;for(var
e
in
c)switch(e){case"rdonly":b|=a.O_RDONLY;break;case"wronly":b|=a.O_WRONLY;break;case"append":b|=a.O_WRONLY|a.O_APPEND;break;case"create":b|=a.O_CREAT;break;case"truncate":b|=a.O_TRUNC;break;case"excl":b|=a.O_EXCL;break;case"binary":b|=a.O_BINARY;break;case"text":b|=a.O_TEXT;break;case"nonblock":b|=a.O_NONBLOCK;break}var
d=this.fs.openSync(this.nm(f),b);return new
l(d)};k.prototype.rename=function(b,a){this.fs.renameSync(this.nm(b),this.nm(a))};k.prototype.constructor=k;var
q=t.match(/[^\/]*\//)[0],v=[];if(typeof
module!==ah&&module.exports&&typeof
require!==ah)v.push({path:q,device:new
k(q)});else
v.push({path:q,device:new
h(q)});v.push({path:q+ac,device:new
h(q+ac)});function
ba(b){var
f=aQ(b),b=f.join(m),e=b+m,c;for(var
d=0;d<v.length;d++){var
a=v[d];if(e.search(a.path)==0&&(!c||c.path.length<a.path.length))c={path:a.path,device:a.device,rest:b.substring(a.path.length,b.length)}}return c}function
aB(e,f){var
b=o[e],d=a(f),c=aw(d);b.file.write(b.offset,d,0,c);b.offset+=c;return 0}function
a9(a){var
b=d;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stderr.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.error&&c.error(a)}}function
a_(a){var
b=d;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stdout.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.log&&c.log(a)}}function
x(d,f,e,a){if(b.fds===undefined)b.fds=new
Array();a=a?a:{};var
c={};c.file=e;c.offset=a.append?e.length():0;c.flags=a;c.output=f;b.fds[d]=c;if(!b.fd_last_idx||d>b.fd_last_idx)b.fd_last_idx=d;return d}function
bb(d,c,h){var
a={};while(c){switch(c[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}c=c[2]}if(a.rdonly&&a.wronly)j(d.toString()+Z);if(a.text&&a.binary)j(d.toString()+ap);var
e=ba(d),f=e.device.open(e.rest,a),g=b.fd_last_idx?b.fd_last_idx:0;return x(g+1,aB,f,a)}x(0,aB,new
e(p(0)));x(1,a_,new
e(p(0)));x(2,a9,new
e(p(0)));function
aS(d){var
c=b.fds[d];if(c.flags.wronly)j(af+d+" is writeonly");var
a={file:c.file,offset:c.offset,fd:d,opened:true,out:false,refill:null};o[a.fd]=a;return a.fd}function
av(e){var
d=b.fds[e];if(d.flags.rdonly)j(af+e+" is readonly");var
a={file:d.file,offset:d.offset,fd:e,opened:true,out:true,buffer:c};o[a.fd]=a;return a.fd}function
aT(){var
b=0;for(var
a=0;a<o.length;a++)if(o[a]&&o[a].opened&&o[a].out)b=[0,o[a].fd,b];return b}function
aU(a){return a
instanceof
Array?a[0]:a
instanceof
n?252:B}function
i(d,c,a){b[d+1]=c;if(a)b[a]=c}var
ay={};function
aP(a){if((a.t&6)!=0)as(a);return a.c}function
aY(a,b){ay[aP(a)]=b;return 0}function
aA(a){return a}function
ax(a){return ay[a]}function
a8(a){if(a
instanceof
Array)return a;if(d.RangeError&&a
instanceof
d.RangeError&&a.message&&a.message.match(/maximum call stack/i))return aA(b.Stack_overflow);if(d.InternalError&&a
instanceof
d.InternalError&&a.message&&a.message.match(/too much recursion/i))return aA(b.Stack_overflow);if(a
instanceof
d.Error&&ax(D))return[0,ax(D),a];return[0,b.Failure,G(String(a))]}var
I=[f,a($),-2],J=[f,a(S),-11];i(11,[f,a(Y),-12],Y);i(10,J,S);i(9,[f,a(ae),-10],ae);i(8,[f,a(ai),-9],ai);i(7,[f,a(ad),-8],ad);i(6,[f,a(ag),-7],ag);i(5,[f,a(ab),-6],ab);i(4,[f,a(ak),-5],ak);i(3,[f,a(an),-4],an);i(2,[f,a(aj),-3],aj);i(1,I,$);i(0,[f,a(R),-1],R);u(0);aS(0);av(1);av(2);u(0);u(0);var
K=[0,0],aH=a("Js.Error"),aM=a("canvas"),aJ=a("img"),aK=a("Dom_html.Canvas_not_available"),aN=[0,a("main.ml"),9,20];function
L(a){K[1]=[0,a,K[1]];return 0}var
y=d,M=null,aG=y.Array,N=[f,aH,u(0)],z=[0,N,{}],aF=undefined,aE=aU(z)===f?z:z[1];aY(a(D),aE);(function(a){throw a});L(function(a){return a[1]===N?[0,G(a[2].toString())]:0});L(function(a){return a
instanceof
aG?0:[0,G(a.toString())]});var
A=y.document,aI="2d";function
O(b,a){return b.createElement(a.toString())}var
aL=[f,aK,u(0)];y.HTMLElement===aF;var
Q=A.getElementById("gui");if(Q==M)throw[0,J,aN];var
r=O(A,aM);if(1-(1-(r.getContext==M?1:0)))throw aL;r.width=B;r.height=B;Q.appendChild(r);var
aO=r.getContext(aI),P=O(A,aJ);P.src="cat.png";aO.drawImage(P,aa,aa);function
aD(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{aR(d)}catch(a){a=a8(a);if(a[1]!==I)throw a}var
a=c;continue}return 0}}aD(aT(0));return}(function(){return this}()));
